"""initial schema

Revision ID: 2441eddce1b9
Revises: 
Create Date: 2026-10-05 14:41:16.364136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2441eddce1b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banners'))
    )
    op.create_index('ix_banners_published_sort', 'banners', ['is_published', 'sort_order'], unique=False)
    op.create_table('blog_posts',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_posts'))
    )
    op.create_index('ix_blog_posts_published_at', 'blog_posts', ['is_published', 'published_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_title'), 'blog_posts', ['title'], unique=False)
    op.create_index('uq_blog_posts_slug_active', 'blog_posts', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('contact_submissions',
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'closed', name='lead_status'), nullable=False),
    sa.Column('source_path', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_submissions'))
    )
    op.create_index(op.f('ix_contact_submissions_email'), 'contact_submissions', ['email'], unique=False)
    op.create_index(op.f('ix_contact_submissions_status'), 'contact_submissions', ['status'], unique=False)
    op.create_index('ix_contact_submissions_status_created', 'contact_submissions', ['status', 'created_at'], unique=False)
    op.create_table('course_categories',
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['course_categories.id'], name=op.f('fk_course_categories_parent_id_course_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_categories'))
    )
    op.create_index(op.f('ix_course_categories_is_published'), 'course_categories', ['is_published'], unique=False)
    op.create_index(op.f('ix_course_categories_name'), 'course_categories', ['name'], unique=False)
    op.create_index(op.f('ix_course_categories_parent_id'), 'course_categories', ['parent_id'], unique=False)
    op.create_index('uq_course_categories_slug_active', 'course_categories', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('faqs',
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faqs'))
    )
    op.create_index('ix_faqs_published_sort', 'faqs', ['is_published', 'sort_order'], unique=False)
    op.create_table('homepage_sections',
    sa.Column('section_key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homepage_sections'))
    )
    op.create_index(op.f('ix_homepage_sections_is_published'), 'homepage_sections', ['is_published'], unique=False)
    op.create_index('uq_homepage_sections_key_active', 'homepage_sections', ['section_key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index('uq_permissions_code_active', 'permissions', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('product_categories',
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], name=op.f('fk_product_categories_parent_id_product_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories'))
    )
    op.create_index(op.f('ix_product_categories_is_published'), 'product_categories', ['is_published'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=False)
    op.create_index(op.f('ix_product_categories_parent_id'), 'product_categories', ['parent_id'], unique=False)
    op.create_index('uq_product_categories_slug_active', 'product_categories', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('roles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index('uq_roles_code_active', 'roles', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('seo_settings',
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('meta_title', sa.String(length=180), nullable=True),
    sa.Column('meta_description', sa.String(length=320), nullable=True),
    sa.Column('og_image_url', sa.String(length=500), nullable=True),
    sa.Column('canonical_path', sa.String(length=255), nullable=True),
    sa.Column('robots', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_settings'))
    )
    op.create_index('ix_seo_settings_entity', 'seo_settings', ['entity_type', 'entity_id'], unique=False)
    op.create_index('uq_seo_settings_path_active', 'seo_settings', ['path'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('service_categories',
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['service_categories.id'], name=op.f('fk_service_categories_parent_id_service_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_categories'))
    )
    op.create_index(op.f('ix_service_categories_is_published'), 'service_categories', ['is_published'], unique=False)
    op.create_index(op.f('ix_service_categories_name'), 'service_categories', ['name'], unique=False)
    op.create_index(op.f('ix_service_categories_parent_id'), 'service_categories', ['parent_id'], unique=False)
    op.create_index('uq_service_categories_slug_active', 'service_categories', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('social_links',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_links'))
    )
    op.create_index('ix_social_links_published_sort', 'social_links', ['is_published', 'sort_order'], unique=False)
    op.create_table('testimonials',
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('author_role', sa.String(length=150), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('business_area', sa.Enum('marketing-advertising', 'technology-digital-products', 'education-academy', 'business-solutions', name='business_area'), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name=op.f('ck_testimonials_rating_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testimonials'))
    )
    op.create_index(op.f('ix_testimonials_business_area'), 'testimonials', ['business_area'], unique=False)
    op.create_index('ix_testimonials_published_sort', 'testimonials', ['is_published', 'sort_order'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_index('uq_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('activity_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_activity_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_user_id'), 'activity_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_activity_logs_created_at', 'activity_logs', ['created_at'], unique=False)
    op.create_index('ix_activity_logs_entity', 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('carts',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('guest_token', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(user_id IS NOT NULL AND guest_token IS NULL) OR (user_id IS NULL AND guest_token IS NOT NULL)', name=op.f('ck_carts_one_owner')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_carts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts'))
    )
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    op.create_index('uq_carts_guest_active', 'carts', ['guest_token'], unique=True, postgresql_where=sa.text('guest_token IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('uq_carts_user_active', 'carts', ['user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL AND deleted_at IS NULL'))
    op.create_table('courses',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('business_area', sa.Enum('marketing-advertising', 'technology-digital-products', 'education-academy', 'business-solutions', name='business_area', create_type=False), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('duration_label', sa.String(length=80), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price_amount IS NULL OR price_amount >= 0', name=op.f('ck_courses_price_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['course_categories.id'], name=op.f('fk_courses_category_id_course_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index(op.f('ix_courses_business_area'), 'courses', ['business_area'], unique=False)
    op.create_index(op.f('ix_courses_category_id'), 'courses', ['category_id'], unique=False)
    op.create_index(op.f('ix_courses_is_published'), 'courses', ['is_published'], unique=False)
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=False)
    op.create_index('uq_courses_slug_active', 'courses', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('customer_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customer_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_profiles'))
    )
    op.create_index('uq_customer_profiles_user_active', 'customer_profiles', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'cancelled', 'fulfilled', 'refunded', name='order_status'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('subtotal >= 0 AND total >= 0', name=op.f('ck_orders_totals_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index('ix_orders_placed_at', 'orders', ['placed_at'], unique=False)
    op.create_index('ix_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_index('uq_orders_order_number', 'orders', ['order_number'], unique=True)
    op.create_table('products',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('business_area', sa.Enum('marketing-advertising', 'technology-digital-products', 'education-academy', 'business-solutions', name='business_area', create_type=False), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_type', sa.Enum('software', 'saas', 'digital', 'ecommerce', name='product_type'), nullable=False),
    sa.Column('listing_channel', sa.Enum('technology', 'shop', 'both', name='listing_channel'), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('is_downloadable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('track_stock', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_products_category_id_product_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_business_area'), 'products', ['business_area'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_is_published'), 'products', ['is_published'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index('ix_products_type_channel', 'products', ['product_type', 'listing_channel'], unique=False)
    op.create_index('uq_products_sku_active', 'products', ['sku'], unique=True, postgresql_where=sa.text('sku IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('uq_products_slug_active', 'products', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('services',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('business_area', sa.Enum('marketing-advertising', 'technology-digital-products', 'education-academy', 'business-solutions', name='business_area', create_type=False), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], name=op.f('fk_services_category_id_service_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index('ix_services_area_published', 'services', ['business_area', 'is_published'], unique=False)
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index('uq_services_slug_active', 'services', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('addresses',
    sa.Column('customer_profile_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('line1', sa.String(length=200), nullable=False),
    sa.Column('line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], name=op.f('fk_addresses_customer_profile_id_customer_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index(op.f('ix_addresses_customer_profile_id'), 'addresses', ['customer_profile_id'], unique=False)
    op.create_index('uq_addresses_default_active', 'addresses', ['customer_profile_id'], unique=True, postgresql_where=sa.text('is_default AND deleted_at IS NULL'))
    op.create_table('course_modules',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_modules_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_modules'))
    )
    op.create_index(op.f('ix_course_modules_course_id'), 'course_modules', ['course_id'], unique=False)
    op.create_table('marketing_campaign_requests',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'closed', name='lead_status', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_marketing_campaign_requests_service_id_services'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_marketing_campaign_requests_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketing_campaign_requests'))
    )
    op.create_index(op.f('ix_marketing_campaign_requests_email'), 'marketing_campaign_requests', ['email'], unique=False)
    op.create_index(op.f('ix_marketing_campaign_requests_service_id'), 'marketing_campaign_requests', ['service_id'], unique=False)
    op.create_index('ix_marketing_campaign_requests_status_created', 'marketing_campaign_requests', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_marketing_campaign_requests_user_id'), 'marketing_campaign_requests', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', name='payment_status'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payments_amount_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('ix_payments_order_status', 'payments', ['order_id', 'status'], unique=False)
    op.create_table('product_features',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_features_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_features'))
    )
    op.create_index(op.f('ix_product_features_product_id'), 'product_features', ['product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('option_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('id', 'product_id', name='uq_product_variants_id_product')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index('uq_product_variants_sku_active', 'product_variants', ['sku'], unique=True, postgresql_where=sa.text('sku IS NOT NULL AND deleted_at IS NULL'))
    op.create_table('quote_requests',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('business_area', sa.Enum('marketing-advertising', 'technology-digital-products', 'education-academy', 'business-solutions', name='business_area', create_type=False), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('new', 'reviewing', 'quoted', 'accepted', 'declined', 'closed', name='quote_status'), nullable=False),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('response_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['responded_by_user_id'], ['users.id'], name=op.f('fk_quote_requests_responded_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_quote_requests_service_id_services'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quote_requests_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_requests'))
    )
    op.create_index(op.f('ix_quote_requests_email'), 'quote_requests', ['email'], unique=False)
    op.create_index(op.f('ix_quote_requests_service_id'), 'quote_requests', ['service_id'], unique=False)
    op.create_index('ix_quote_requests_status_created', 'quote_requests', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_quote_requests_user_id'), 'quote_requests', ['user_id'], unique=False)
    op.create_table('service_enquiries',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'closed', name='lead_status', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_enquiries_service_id_services'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_service_enquiries_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_enquiries'))
    )
    op.create_index(op.f('ix_service_enquiries_email'), 'service_enquiries', ['email'], unique=False)
    op.create_index(op.f('ix_service_enquiries_service_id'), 'service_enquiries', ['service_id'], unique=False)
    op.create_index('ix_service_enquiries_status_created', 'service_enquiries', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_service_enquiries_user_id'), 'service_enquiries', ['user_id'], unique=False)
    op.create_table('service_packages',
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('billing_period', sa.Enum('one_time', 'monthly', 'yearly', 'custom', name='billing_period'), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_packages_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_packages'))
    )
    op.create_index(op.f('ix_service_packages_is_published'), 'service_packages', ['is_published'], unique=False)
    op.create_index(op.f('ix_service_packages_service_id'), 'service_packages', ['service_id'], unique=False)
    op.create_index('uq_service_packages_service_slug_active', 'service_packages', ['service_id', 'slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('cart_items',
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.Enum('product', 'package', 'course', name='order_item_type'), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('package_id', sa.Uuid(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(item_type = 'product' AND product_id IS NOT NULL AND package_id IS NULL AND course_id IS NULL) OR (item_type = 'package' AND package_id IS NOT NULL AND product_id IS NULL AND course_id IS NULL) OR (item_type = 'course' AND course_id IS NOT NULL AND product_id IS NULL AND package_id IS NULL)", name=op.f('ck_cart_items_one_target')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_cart_items_quantity_positive')),
    sa.CheckConstraint('variant_id IS NULL OR product_id IS NOT NULL', name=op.f('ck_cart_items_variant_requires_product')),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_items_cart_id_carts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_cart_items_course_id_courses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['package_id'], ['service_packages.id'], name=op.f('fk_cart_items_package_id_service_packages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cart_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id', 'product_id'], ['product_variants.id', 'product_variants.product_id'], name='fk_cart_items_variant_product'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items'))
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_table('course_lessons',
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.Enum('text', 'video_url', 'file', name='lesson_content_type'), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_preview', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], name=op.f('fk_course_lessons_module_id_course_modules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_lessons'))
    )
    op.create_index(op.f('ix_course_lessons_module_id'), 'course_lessons', ['module_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.Enum('product', 'package', 'course', name='order_item_type', create_type=False), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('package_id', sa.Uuid(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(item_type = 'product' AND product_id IS NOT NULL AND package_id IS NULL AND course_id IS NULL) OR (item_type = 'package' AND package_id IS NOT NULL AND product_id IS NULL AND course_id IS NULL) OR (item_type = 'course' AND course_id IS NOT NULL AND product_id IS NULL AND package_id IS NULL)", name=op.f('ck_order_items_one_target')),
    sa.CheckConstraint('quantity > 0 AND unit_price >= 0 AND line_total >= 0', name=op.f('ck_order_items_amounts_valid')),
    sa.CheckConstraint('variant_id IS NULL OR product_id IS NOT NULL', name=op.f('ck_order_items_variant_requires_product')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_order_items_course_id_courses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['service_packages.id'], name=op.f('fk_order_items_package_id_service_packages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id', 'product_id'], ['product_variants.id', 'product_variants.product_id'], name='fk_order_items_variant_product'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_table('package_features',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['service_packages.id'], name=op.f('fk_package_features_package_id_service_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_features'))
    )
    op.create_index(op.f('ix_package_features_package_id'), 'package_features', ['package_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', name='payment_status', create_type=False), nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payment_transactions_amount_non_negative')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_transactions_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_transactions'))
    )
    op.create_index(op.f('ix_payment_transactions_payment_id'), 'payment_transactions', ['payment_id'], unique=False)
    op.create_index('ix_payment_transactions_provider_reference', 'payment_transactions', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.create_table('product_images',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_images_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id', 'product_id'], ['product_variants.id', 'product_variants.product_id'], name='fk_product_images_variant_product', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_images'))
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_images_variant_id'), 'product_images', ['variant_id'], unique=False)
    op.create_index('uq_product_images_primary', 'product_images', ['product_id'], unique=True, postgresql_where=sa.text('is_primary AND variant_id IS NULL AND deleted_at IS NULL'))
    op.create_index('uq_product_images_variant_primary', 'product_images', ['variant_id'], unique=True, postgresql_where=sa.text('is_primary AND variant_id IS NOT NULL AND deleted_at IS NULL'))
    op.create_table('product_prices',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compare_at_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('billing_period', sa.Enum('one_time', 'monthly', 'yearly', 'custom', name='billing_period', create_type=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_product_prices_amount_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_prices_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id', 'product_id'], ['product_variants.id', 'product_variants.product_id'], name='fk_product_prices_variant_product', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_prices'))
    )
    op.create_index(op.f('ix_product_prices_product_id'), 'product_prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_prices_variant_id'), 'product_prices', ['variant_id'], unique=False)
    op.create_index('uq_product_prices_active_product', 'product_prices', ['product_id'], unique=True, postgresql_where=sa.text('variant_id IS NULL AND is_active AND deleted_at IS NULL'))
    op.create_index('uq_product_prices_active_variant', 'product_prices', ['variant_id'], unique=True, postgresql_where=sa.text('variant_id IS NOT NULL AND is_active AND deleted_at IS NULL'))
    op.create_table('course_enrollments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'completed', 'cancelled', name='enrollment_status'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'order', name='enrollment_source'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_enrollments_course_id_courses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_course_enrollments_order_item_id_order_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_course_enrollments_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_enrollments'))
    )
    op.create_index(op.f('ix_course_enrollments_course_id'), 'course_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_order_item_id'), 'course_enrollments', ['order_item_id'], unique=False)
    op.create_index('ix_course_enrollments_status', 'course_enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_course_enrollments_user_id'), 'course_enrollments', ['user_id'], unique=False)
    op.create_index('uq_course_enrollments_order_item', 'course_enrollments', ['order_item_id'], unique=True, postgresql_where=sa.text('order_item_id IS NOT NULL'))
    op.create_index('uq_course_enrollments_user_course_active', 'course_enrollments', ['user_id', 'course_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('course_resources',
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(course_id IS NOT NULL AND lesson_id IS NULL) OR (course_id IS NULL AND lesson_id IS NOT NULL)', name=op.f('ck_course_resources_one_parent')),
    sa.CheckConstraint('file_url IS NOT NULL OR external_url IS NOT NULL', name=op.f('ck_course_resources_resource_location')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_resources_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], name=op.f('fk_course_resources_lesson_id_course_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_resources'))
    )
    op.create_index(op.f('ix_course_resources_course_id'), 'course_resources', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_resources_lesson_id'), 'course_resources', ['lesson_id'], unique=False)
    op.create_table('certificates',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('certificate_number', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('issued', 'revoked', name='certificate_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['course_enrollments.id'], name=op.f('fk_certificates_enrollment_id_course_enrollments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates'))
    )
    op.create_index(op.f('ix_certificates_status'), 'certificates', ['status'], unique=False)
    op.create_index('uq_certificates_enrollment', 'certificates', ['enrollment_id'], unique=True)
    op.create_index('uq_certificates_number', 'certificates', ['certificate_number'], unique=True)
    op.create_table('course_progress',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['course_enrollments.id'], name=op.f('fk_course_progress_enrollment_id_course_enrollments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], name=op.f('fk_course_progress_lesson_id_course_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_progress'))
    )
    op.create_index(op.f('ix_course_progress_lesson_id'), 'course_progress', ['lesson_id'], unique=False)
    op.create_index('uq_course_progress_enrollment_lesson', 'course_progress', ['enrollment_id', 'lesson_id'], unique=True)
    # ### end Alembic commands ###
    op.execute(
        sa.text(
            """
            CREATE OR REPLACE FUNCTION set_updated_at()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                NEW.updated_at = now();
                RETURN NEW;
            END;
            $$;
            """
        )
    )
    tables_with_updated_at = op.get_bind().execute(
        sa.text(
            """
            SELECT table_name
            FROM information_schema.columns
            WHERE table_schema = 'public' AND column_name = 'updated_at'
            ORDER BY table_name
            """
        )
    ).scalars()
    for table_name in tables_with_updated_at:
        op.execute(
            sa.text(
                f"CREATE TRIGGER set_{table_name}_updated_at "
                f"BEFORE UPDATE ON {table_name} "
                "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_course_progress_enrollment_lesson', table_name='course_progress')
    op.drop_index(op.f('ix_course_progress_lesson_id'), table_name='course_progress')
    op.drop_table('course_progress')
    op.drop_index('uq_certificates_number', table_name='certificates')
    op.drop_index('uq_certificates_enrollment', table_name='certificates')
    op.drop_index(op.f('ix_certificates_status'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_course_resources_lesson_id'), table_name='course_resources')
    op.drop_index(op.f('ix_course_resources_course_id'), table_name='course_resources')
    op.drop_table('course_resources')
    op.drop_index('uq_course_enrollments_user_course_active', table_name='course_enrollments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_course_enrollments_order_item', table_name='course_enrollments', postgresql_where=sa.text('order_item_id IS NOT NULL'))
    op.drop_index(op.f('ix_course_enrollments_user_id'), table_name='course_enrollments')
    op.drop_index('ix_course_enrollments_status', table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_order_item_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_course_id'), table_name='course_enrollments')
    op.drop_table('course_enrollments')
    op.drop_index('uq_product_prices_active_variant', table_name='product_prices', postgresql_where=sa.text('variant_id IS NOT NULL AND is_active AND deleted_at IS NULL'))
    op.drop_index('uq_product_prices_active_product', table_name='product_prices', postgresql_where=sa.text('variant_id IS NULL AND is_active AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_product_prices_variant_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_product_id'), table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_index('uq_product_images_variant_primary', table_name='product_images', postgresql_where=sa.text('is_primary AND variant_id IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('uq_product_images_primary', table_name='product_images', postgresql_where=sa.text('is_primary AND variant_id IS NULL AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_product_images_variant_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_provider_reference', table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_package_features_package_id'), table_name='package_features')
    op.drop_table('package_features')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_course_lessons_module_id'), table_name='course_lessons')
    op.drop_table('course_lessons')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index('uq_service_packages_service_slug_active', table_name='service_packages', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_service_packages_service_id'), table_name='service_packages')
    op.drop_index(op.f('ix_service_packages_is_published'), table_name='service_packages')
    op.drop_table('service_packages')
    op.drop_index(op.f('ix_service_enquiries_user_id'), table_name='service_enquiries')
    op.drop_index('ix_service_enquiries_status_created', table_name='service_enquiries')
    op.drop_index(op.f('ix_service_enquiries_service_id'), table_name='service_enquiries')
    op.drop_index(op.f('ix_service_enquiries_email'), table_name='service_enquiries')
    op.drop_table('service_enquiries')
    op.drop_index(op.f('ix_quote_requests_user_id'), table_name='quote_requests')
    op.drop_index('ix_quote_requests_status_created', table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_service_id'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_email'), table_name='quote_requests')
    op.drop_table('quote_requests')
    op.drop_index('uq_product_variants_sku_active', table_name='product_variants', postgresql_where=sa.text('sku IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_features_product_id'), table_name='product_features')
    op.drop_table('product_features')
    op.drop_index('ix_payments_order_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_marketing_campaign_requests_user_id'), table_name='marketing_campaign_requests')
    op.drop_index('ix_marketing_campaign_requests_status_created', table_name='marketing_campaign_requests')
    op.drop_index(op.f('ix_marketing_campaign_requests_service_id'), table_name='marketing_campaign_requests')
    op.drop_index(op.f('ix_marketing_campaign_requests_email'), table_name='marketing_campaign_requests')
    op.drop_table('marketing_campaign_requests')
    op.drop_index(op.f('ix_course_modules_course_id'), table_name='course_modules')
    op.drop_table('course_modules')
    op.drop_index('uq_addresses_default_active', table_name='addresses', postgresql_where=sa.text('is_default AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_addresses_customer_profile_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('user_roles')
    op.drop_index('uq_services_slug_active', table_name='services', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.drop_index('ix_services_area_published', table_name='services')
    op.drop_table('services')
    op.drop_table('role_permissions')
    op.drop_index('uq_products_slug_active', table_name='products', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_products_sku_active', table_name='products', postgresql_where=sa.text('sku IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('ix_products_type_channel', table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_published'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_business_area'), table_name='products')
    op.drop_table('products')
    op.drop_index('uq_orders_order_number', table_name='orders')
    op.drop_index('ix_orders_user_status', table_name='orders')
    op.drop_index('ix_orders_placed_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('uq_customer_profiles_user_active', table_name='customer_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('customer_profiles')
    op.drop_index('uq_courses_slug_active', table_name='courses', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_index(op.f('ix_courses_is_published'), table_name='courses')
    op.drop_index(op.f('ix_courses_category_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_business_area'), table_name='courses')
    op.drop_table('courses')
    op.drop_index('uq_carts_user_active', table_name='carts', postgresql_where=sa.text('user_id IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('uq_carts_guest_active', table_name='carts', postgresql_where=sa.text('guest_token IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index('ix_activity_logs_entity', table_name='activity_logs')
    op.drop_index('ix_activity_logs_created_at', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('uq_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_testimonials_published_sort', table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_business_area'), table_name='testimonials')
    op.drop_table('testimonials')
    op.drop_index('ix_social_links_published_sort', table_name='social_links')
    op.drop_table('social_links')
    op.drop_index('uq_service_categories_slug_active', table_name='service_categories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_service_categories_parent_id'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_name'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_is_published'), table_name='service_categories')
    op.drop_table('service_categories')
    op.drop_index('uq_seo_settings_path_active', table_name='seo_settings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_seo_settings_entity', table_name='seo_settings')
    op.drop_table('seo_settings')
    op.drop_index('uq_roles_code_active', table_name='roles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('roles')
    op.drop_index('uq_product_categories_slug_active', table_name='product_categories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_product_categories_parent_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_is_published'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index('uq_permissions_code_active', table_name='permissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('permissions')
    op.drop_index('uq_homepage_sections_key_active', table_name='homepage_sections', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_homepage_sections_is_published'), table_name='homepage_sections')
    op.drop_table('homepage_sections')
    op.drop_index('ix_faqs_published_sort', table_name='faqs')
    op.drop_table('faqs')
    op.drop_index('uq_course_categories_slug_active', table_name='course_categories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_course_categories_parent_id'), table_name='course_categories')
    op.drop_index(op.f('ix_course_categories_name'), table_name='course_categories')
    op.drop_index(op.f('ix_course_categories_is_published'), table_name='course_categories')
    op.drop_table('course_categories')
    op.drop_index('ix_contact_submissions_status_created', table_name='contact_submissions')
    op.drop_index(op.f('ix_contact_submissions_status'), table_name='contact_submissions')
    op.drop_index(op.f('ix_contact_submissions_email'), table_name='contact_submissions')
    op.drop_table('contact_submissions')
    op.drop_index('uq_blog_posts_slug_active', table_name='blog_posts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_blog_posts_title'), table_name='blog_posts')
    op.drop_index('ix_blog_posts_published_at', table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index('ix_banners_published_sort', table_name='banners')
    op.drop_table('banners')
    # ### end Alembic commands ###
    op.execute(sa.text("DROP FUNCTION IF EXISTS set_updated_at()"))
    bind = op.get_bind()
    for enum_name in (
        "billing_period",
        "business_area",
        "certificate_status",
        "enrollment_source",
        "enrollment_status",
        "lead_status",
        "lesson_content_type",
        "listing_channel",
        "order_item_type",
        "order_status",
        "payment_status",
        "product_type",
        "quote_status",
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
